### ISSUE TITLE
Улучшить наименования поле в данных клиента

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-admin-tech#162]
"stocknumPrefix" - "Stock Number Prefix" <- Это чекбокс
"stocknumSuffix" - "Stock Number Suffix" <- Это чекбокс
"stocknumLast6ofVIN" - "Stock Number Last 6 of VIN simbols" <- Это радиобаттон
"stocknumLast8ofVIN" - "Stock Number Last 8 of VIN simbols" <- Это радиобаттон
"stocknumFixedDigits" - "Stock Number Fixed Digits" <- Это чекбокс

"stocknumtiPrefix" - "Stock Number Prefix" <- Это поле ввода текста
"stocknumtiSuffix" - "Stock Number Suffix" <- Это поле ввода текста
"stocknumtiLast6ofVIN" - "Stock Number Last 6 of VIN simbols" <- Это поле ввода текста
"stocknumtiLast8ofVIN" - "Stock Number Last 8 of VIN simbols" <- Это поле ввода текста
"stocknumtiFixedDigits" - "Stock Number Fixed Digits" <- Это поле ввода текста

"dealType" - "Deal Type" - Combobox
"dealStatus" - "Deal Status"- Combobox
"feeDefDocumentation" - "Documentation Fee" - Editbox ( currency)
"feeDefvehiclePack" - "Vehicle Pack Fee" - Editbox ( currency)
"feeDefTitle" - "Title Fee" - Editbox ( currency)
"feeDefTag" - "Tag Fee" - Editbox ( currency)
"feeDefTransfer" - "Transfer Fee" - Editbox ( currency)
"feeDefSpareTag" - "Spare Tag Fee" - Editbox ( currency)
"feeDefSpareTransferTag" - "Spare Transfer Tag Fee" - Editbox ( currency)
"taxDefStateVehicleTaxRate" - "State Vehicle Tax Rate" - Editbox ( currency)
"stocknumSequental" - "Stock Number is Sequental" - Checkbox
"stocknumPrefix" - "Stock Number Prefix" - Editbox
"stocknumSuffix" - "Stock Number Suffix" - Editbox
"stocknumLast6ofVIN" - "Stock Number Last 6 of VIN simbols" - Radiobutton
"stocknumLast8ofVIN" - "Stock Number Last 8 of VIN simbols" - Radiobutton
"stocknumFixedDigits" - "Stock Number Fixed Digits" - Editbox ( number)
"stocknumtiSequental" - "Stock Number Is Sequental" - Checkbox
"stocknumtiPrefix" - "Stock Number Prefix" - Editbox
"stocknumtiSuffix" - "Stock Number Suffix" - Editbox
"stocknumtiLast6ofVIN" - "Stock Number Last 6 of VIN simbols" - Editbox
"stocknumtiLast8ofVIN" - "Stock Number Last 8 of VIN simbols" - Editbox
"stocknumtiFixedDigits" - "Stock Number Fixed Digits" - Checkbox
"stocknumtiFromSoldVehicle" - "Stock Number From Sold Vehicle" - Checkbox
"accountStartNumber" - "Account Start Number" - Editbox
"accountFixedDigits" - "Account Fixed Digits" - Editbox ( number)
"accountPrefix" - "Account Prefix" - Editbox
"accountSuffix" - "Account Suffix" - Editbox
"accountLateFeeMin" - "Account Late Fee Min" - Editbox ( currency)
"accountLateFeeMax" - "Account Late Fee Max" - Editbox ( currency)
"accountLateFeePercentage" - "Account Late Fee Percentage" - Editbox ( number)
"accountLateFeeGracePeriod" - "Account Late Fee Grace Period" - Editbox ( number)
"contractDefInterestRate" - "Contract Default Interest Rate" - Editbox ( number)
"contractPaymentFrequency" - "Contract Payment Frequency" - Editbox ( number)
"leaseMoneyFactor" - "Lease Money Factor" - Editbox ( number)
"leaseDefaultMileage" - "Lease Default Mileage" - Editbox ( number)
"leaseOverageAmount" - "Lease Overage Amount" - Editbox ( number)
"leaseTerm" - "Lease Term" - Combobox
"leasePaymentFrequency" - "Lease Payment Frequency" - Combobox

**Comment by kamabzalov** [comment]
@JSDID как начнете делать, дайте знать - дам api (или enum)

**Comment by JSDID** [comment]
Добре)

**Comment by kamabzalov** [comment]
Аналогичная задача в CRM - [https://github.com/kamabzalov/admss-crm/issues/188](https://github.com/kamabzalov/admss-crm/issues/188)
